name: Backend

on:
  push:
    paths: [backend/**]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-packages
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest

      - name: Install mysql-workbench
        run: sudo ansible -m apt -a deb=https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community_8.0.22-1ubuntu20.04_amd64.deb localhost

      - name: Install npm deps
        run: xvfb-run yarn install --inline-builds

      - name: Log in to docker
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.GITHUB_TOKEN }} --password-stdin

      - name: Link config file
        run: |
          cat << EOF > resources/config.edn
          {:db {} :key nil}
          EOF

      - name: Run tests
        run: yarn workspace @locket/backend test

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: backend/target/coverage/

      - name: build
        run: clojure -Auberjar

      - uses: actions/upload-artifact@v2
        with:
          name: uberjar
          path: backend/target/*-standalone.jar
